services:
  mockup-template-project:
    image: ghcr.io/m6o4solutions/mockup-template-project:latest
    container_name: mockup-template-project
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockup-template-project.rule=Host(`mockup-template.m6o4solutions.com`)"
      - "traefik.http.routers.mockup-template-project.entrypoints=websecure"
      - "traefik.http.routers.mockup-template-project.tls.certresolver=letsencrypt"
      - "traefik.http.services.mockup-template-project.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik-network
